language: node_js
node_js:
  - 8
  - 9

cache:
  directorioes:
    - node_modules

install:
  - npm install

script:
  - npm run test
  - npm run build
  - npm run predeploy

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: './storybook-static'
  on:
    branch: master
